### PR TITLE
Added a toCamelCase function

### PR DESCRIPTION
**Pull request by TheHandsomeCoder**
Is needed to correctly map dash deliminated fields and allow them to be filtered

### CODE REVIEW

**Comment by gr0uch** [comment]
Looks like there are some concerns:
- If string inflection is turned off, don't touch the names.
- I think there are other queries than `match` that will need to be inflected.
- Use the `inflection` library that's already required rather than rolling your own.

**Comment by TheHandsomeCoder** [comment]
That seems legit actually. I'll go back this afternoon and take a more indepth look.

**Comment by TheHandsomeCoder** [comment]
Rather than camelize each entry in the helper.js file, would it be better to do this when creating the query object? Check once to see if string inflection is turned on and camalize the queries before it's sent to the helper?

**Comment by gr0uch** [comment]
@TheHandsomeCoder it shouldn't try to inflect certain queries expected by the JSON API spec such as limit and offset, it should only inflect field names and just those parts. It's only filter, sort, and include which use field names as far as I'm aware.

**Comment by TheHandsomeCoder** [comment]
Pull request updated

**Comment by TheHandsomeCoder** [comment]
Updated the pull request. It seems to be working correctly at least locally and the packaged tests are passing

**Comment by gr0uch** [comment]
Nice work! :beer:

**Pull request merged**
