### PR TITLE
Add more granular type inflection controls

### PR DESCRIPTION
**Pull request by rhettl**
I made sure all original tests pass and added some other tests (though unsure if you will like the format) to the end which will fail without `inflectType: { animal: false }` in the serializer options. 

I'm happy to make changes if you don't like some of it or how I implemented.

### CODE REVIEW

**Comment by rhettl** [comment]
Forgot to reference #57

**Comment by rhettl** [comment]
Found problem in `mapId` function throwing `409`... fixing

**Comment by rhettl** [comment]
Correction, I just did my setting wrong. All is good with this

**Comment by gr0uch** [comment]
Perfect! Will merge/release. Sorry for delay.

**Pull request merged**
